package com.shamil.cloudvault.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

// Modern Azure/Cloud Palette
val PrimaryLight = Color(0xFF0061A4)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD1E4FF)
val OnPrimaryContainerLight = Color(0xFF001D36)

val SecondaryLight = Color(0xFF535F70)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD7E3F7)
val OnSecondaryContainerLight = Color(0xFF101C2B)

val TertiaryLight = Color(0xFF6B5778)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFF2DAFF)
val OnTertiaryContainerLight = Color(0xFF251431)

val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

val BackgroundLight = Color(0xFFFDFBFF)
val OnBackgroundLight = Color(0xFF1A1C1E)
val SurfaceLight = Color(0xFFFDFBFF)
val OnSurfaceLight = Color(0xFF1A1C1E)
val SurfaceVariantLight = Color(0xFFDFE2EB)
val OnSurfaceVariantLight = Color(0xFF43474E)
val OutlineLight = Color(0xFF73777F)

// Dark Theme
val PrimaryDark = Color(0xFF9ECAFF)
val OnPrimaryDark = Color(0xFF003258)
val PrimaryContainerDark = Color(0xFF00497D)
val OnPrimaryContainerDark = Color(0xFFD1E4FF)

val SecondaryDark = Color(0xFFBBC7DB)
val OnSecondaryDark = Color(0xFF253140)
val SecondaryContainerDark = Color(0xFF3B4858)
val OnSecondaryContainerDark = Color(0xFFD7E3F7)

val TertiaryDark = Color(0xFFD6BEE4)
val OnTertiaryDark = Color(0xFF3B2948)
val TertiaryContainerDark = Color(0xFF523F5F)
val OnTertiaryContainerDark = Color(0xFFF2DAFF)

val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)

val BackgroundDark = Color(0xFF1A1C1E)
val OnBackgroundDark = Color(0xFFE2E2E6)
val SurfaceDark = Color(0xFF1A1C1E)
val OnSurfaceDark = Color(0xFFE2E2E6)
val SurfaceVariantDark = Color(0xFF43474E)
val OnSurfaceVariantDark = Color(0xFFC3C7CF)
val OutlineDark = Color(0xFF8D9199)

// --- Theme Style: Forest (Green) ---
val PrimaryLightForest = Color(0xFF006E1C)
val OnPrimaryLightForest = Color(0xFFFFFFFF)
val PrimaryContainerLightForest = Color(0xFF94F990)
val OnPrimaryContainerLightForest = Color(0xFF002204)
val SecondaryLightForest = Color(0xFF53634F)
val OnSecondaryLightForest = Color(0xFFFFFFFF)
val SecondaryContainerLightForest = Color(0xFFD6E8CE)
val OnSecondaryContainerLightForest = Color(0xFF111F0F)
val BackgroundLightForest = Color(0xFFFCFDF6)
val OnBackgroundLightForest = Color(0xFF1A1C19)
val SurfaceLightForest = Color(0xFFFCFDF6)
val OnSurfaceLightForest = Color(0xFF1A1C19)

val PrimaryDarkForest = Color(0xFF79DC77)
val OnPrimaryDarkForest = Color(0xFF00390A)
val PrimaryContainerDarkForest = Color(0xFF005312)
val OnPrimaryContainerDarkForest = Color(0xFF94F990)
val SecondaryDarkForest = Color(0xFFBACCB3)
val OnSecondaryDarkForest = Color(0xFF253423)
val SecondaryContainerDarkForest = Color(0xFF3B4B38)
val OnSecondaryContainerDarkForest = Color(0xFFD6E8CE)
val BackgroundDarkForest = Color(0xFF1A1C19)
val OnBackgroundDarkForest = Color(0xFFE2E3DD)
val SurfaceDarkForest = Color(0xFF1A1C19)
val OnSurfaceDarkForest = Color(0xFFE2E3DD)

// --- Theme Style: Sunset (Red/Orange) ---
val PrimaryLightSunset = Color(0xFF9C4143)
val OnPrimaryLightSunset = Color(0xFFFFFFFF)
val PrimaryContainerLightSunset = Color(0xFFFFDAD9)
val OnPrimaryContainerLightSunset = Color(0xFF400106)
val SecondaryLightSunset = Color(0xFF775655)
val OnSecondaryLightSunset = Color(0xFFFFFFFF)
val SecondaryContainerLightSunset = Color(0xFFFFDAD9)
val OnSecondaryContainerLightSunset = Color(0xFF2C1515)
val BackgroundLightSunset = Color(0xFFFFFBFF)
val OnBackgroundLightSunset = Color(0xFF201A1A)
val SurfaceLightSunset = Color(0xFFFFFBFF)
val OnSurfaceLightSunset = Color(0xFF201A1A)

val PrimaryDarkSunset = Color(0xFFFFB3B2)
val OnPrimaryDarkSunset = Color(0xFF5F1319)
val PrimaryContainerDarkSunset = Color(0xFF7E2A2D)
val OnPrimaryContainerDarkSunset = Color(0xFFFFDAD9)
val SecondaryDarkSunset = Color(0xFFE6BDBC)
val OnSecondaryDarkSunset = Color(0xFF442928)
val SecondaryContainerDarkSunset = Color(0xFF5D3F3E)
val OnSecondaryContainerDarkSunset = Color(0xFFFFDAD9)
val BackgroundDarkSunset = Color(0xFF201A1A)
val OnBackgroundDarkSunset = Color(0xFFEDE0DF)
val SurfaceDarkSunset = Color(0xFF201A1A)
val OnSurfaceDarkSunset = Color(0xFFEDE0DF)

// --- Theme Style: Lavender (Purple) ---
val PrimaryLightLavender = Color(0xFF764B9B)
val OnPrimaryLightLavender = Color(0xFFFFFFFF)
val PrimaryContainerLightLavender = Color(0xFFF1DBFF)
val OnPrimaryContainerLightLavender = Color(0xFF2D0050)
val SecondaryLightLavender = Color(0xFF665A6F)
val OnSecondaryLightLavender = Color(0xFFFFFFFF)
val SecondaryContainerLightLavender = Color(0xFFEEDCF5)
val OnSecondaryContainerLightLavender = Color(0xFF21182A)
val BackgroundLightLavender = Color(0xFFFFFBFF)
val OnBackgroundLightLavender = Color(0xFF1D1B1E)
val SurfaceLightLavender = Color(0xFFFFFBFF)
val OnSurfaceLightLavender = Color(0xFF1D1B1E)

val PrimaryDarkLavender = Color(0xFFDEB7FF)
val OnPrimaryDarkLavender = Color(0xFF451969)
val PrimaryContainerDarkLavender = Color(0xFF5D3281)
val OnPrimaryContainerDarkLavender = Color(0xFFF1DBFF)
val SecondaryDarkLavender = Color(0xFFD1C1D9)
val OnSecondaryDarkLavender = Color(0xFF372D3F)
val SecondaryContainerDarkLavender = Color(0xFF4E4357)
val OnSecondaryContainerDarkLavender = Color(0xFFEEDCF5)
val BackgroundDarkLavender = Color(0xFF1D1B1E)
val OnBackgroundDarkLavender = Color(0xFFE6E1E6)
val SurfaceDarkLavender = Color(0xFF1D1B1E)
val OnSurfaceDarkLavender = Color(0xFFE6E1E6)

